### PR TITLE
update demo.py and darknet2pytorch.py

### PR DESCRIPTION
**Pull request by ajsanjoaquin**
I added torch weights support for demo.py by adding a new argument "-torch" to avoid issues like [this](https://github.com/Tianxiaomo/pytorch-YOLOv4/issues/58) when using demo.py. 

I also fixed the false warning whenever any yolo cfg file is initialized by darknet2pytorch.Darknet when it parses the Linear activation of the convolutional blocks as I mentioned [here](https://github.com/Tianxiaomo/pytorch-YOLOv4/issues/281).

### CODE REVIEW

**Comment by zhu-zhaofei** [comment]
thinks a lot. you are right.it's a good method of solving the problem.

**Comment by t-ibayashi-safie** [comment]
This helps Me alot!
Thank you so match

**Comment by queirozrphl** [comment]
Thats's pretty good. Thank you

**Comment by ajsanjoaquin** [comment]
@Tianxiaomo or any other collaborator, can you please approve the merge? Thank you.

**Comment by beybars1** [comment]
Great! Appreciate your input!

**Comment by Tianxiaomo** [comment]
update demo.py and darknet2pytorch.py

**Comment by waragai-katsunori** [comment]
```
    parser.add_argument('-torch', type=bool, default=false,
                        help='use torch weights')
```

`false` should be `False`

**Pull request merged**
